# Copyright (c) Microsoft. All rights reserved.
"""Observability package - logging, metrics, and exceptions."""

from .exceptions import (
    AgentExecutionError,
    ArchitectError,
    CodeComprehensionError,
    ConfigurationError,
    FileProcessingError,
    FileTooLargeError,
    GitHubError,
    GitHubRateLimitError,
    IngestionError,
    IngestionTimeoutError,
    InvalidRepositoryURLError,
    JobAlreadyExistsError,
    JobError,
    JobNotFoundError,
    LLMConnectionError,
    LLMError,
    LLMRateLimitError,
    LLMResponseError,
    LLMTokenLimitError,
    MissingAPIKeyError,
    MissingRepoBundleError,
    ReportGenerationError,
    RepositoryAccessDeniedError,
    RepositoryNotFoundError,
    WorkflowError,
    WorkflowStateError,
)
from .logging import (
    LogContext,
    MetricsCollector,
    PerformanceTracker,
    configure_logging,
    get_correlation_id,
    get_logger,
    metrics,
    new_correlation_id,
    set_correlation_id,
    track_performance,
)

__all__ = [
    # Logging
    "configure_logging",
    "get_logger",
    "get_correlation_id",
    "set_correlation_id",
    "new_correlation_id",
    "LogContext",
    "PerformanceTracker",
    "track_performance",
    "MetricsCollector",
    "metrics",
    # Exceptions
    "CodeComprehensionError",
    "ConfigurationError",
    "MissingAPIKeyError",
    "GitHubError",
    "RepositoryNotFoundError",
    "RepositoryAccessDeniedError",
    "GitHubRateLimitError",
    "InvalidRepositoryURLError",
    "IngestionError",
    "FileProcessingError",
    "FileTooLargeError",
    "IngestionTimeoutError",
    "LLMError",
    "LLMConnectionError",
    "LLMRateLimitError",
    "LLMResponseError",
    "LLMTokenLimitError",
    "ArchitectError",
    "MissingRepoBundleError",
    "ReportGenerationError",
    "WorkflowError",
    "WorkflowStateError",
    "AgentExecutionError",
    "JobError",
    "JobNotFoundError",
    "JobAlreadyExistsError",
]
